In [1]:
import numpy as np

### How to create an 1d_array

In [2]:
a = np.array((1,2,3,4,5))
a

array([1, 2, 3, 4, 5])

In [3]:
a.dtype

dtype('int32')

#### Set dtype explicity

In [10]:
a = np.array([1,2,3.5,4,5], dtype=np.float64)
a

array([1. , 2. , 3.5, 4. , 5. ])

In [11]:
a.ndim, a.shape, a.size , a.dtype, a.sum()

(1, (5,), 5, dtype('float64'), 15.5)

In [12]:
a = a.astype(np.int32)
a

array([1, 2, 3, 4, 5])

In [13]:
a.dtype

dtype('int32')

### How to create an nd_array

In [23]:
lst = [[1,2,3,4,5],[6,7,8,9,10]]
lst

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [24]:
b = np.array(lst, dtype=np.float64)

In [25]:
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [18]:
b.dtype

dtype('float64')

In [19]:
b.ndim, b.shape, b.size

(2, (2, 5), 10)

### functions of numpy

In [27]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
np.empty((4,4))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.37962117e-306],
       [8.34441742e-308, 1.78022342e-306, 6.23058028e-307,
        9.79107872e-307],
       [6.89807188e-307, 7.56594375e-307, 6.23060065e-307,
        1.78021527e-306],
       [8.34454050e-308, 1.11261027e-306, 1.15706896e-306,
        1.33512173e-306]])

In [30]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [31]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [32]:
np.random.standard_normal((2, 3))

array([[ 0.15266057,  0.2660341 ,  0.25854005],
       [-0.7004932 , -1.04756535, -0.70039571]])

### stacking

In [33]:
a = np.random.standard_normal((2,3))
b = np.random.standard_normal((2,3))

In [34]:
np.vstack([a, b])

array([[ 0.15823867, -1.00335747, -0.28001068],
       [-0.96510076, -0.17377451, -1.05559619],
       [-1.28233293,  0.15816233, -0.82464596],
       [ 0.4808868 , -0.10050224, -0.32330168]])

In [37]:
np.hstack([a,b])

array([[ 0.15823867, -1.00335747, -0.28001068,  0.15823867, -1.00335747,
        -0.28001068, -1.28233293,  0.15816233, -0.82464596],
       [-0.96510076, -0.17377451, -1.05559619, -0.96510076, -0.17377451,
        -1.05559619,  0.4808868 , -0.10050224, -0.32330168]])

In [38]:
a.transpose()

array([[ 0.15823867, -0.96510076],
       [-1.00335747, -0.17377451],
       [-0.28001068, -1.05559619]])

In [39]:
a.T

array([[ 0.15823867, -0.96510076],
       [-1.00335747, -0.17377451],
       [-0.28001068, -1.05559619]])

### dummy array

In [40]:
a = np.array([1, 2, 3, 4])
a.shape, a

((4,), array([1, 2, 3, 4]))

In [41]:
b = a.T
b.shape

(4,)

In [44]:
np.all(b == a)

True

In [45]:
a = np.array([[1, 2, 3, 4]])
a.shape, a

((1, 4), array([[1, 2, 3, 4]]))

In [47]:
b = a.T
b.shape

(4, 1)

In [48]:
np.all(b == a)

False

### save & load

In [49]:
np.save('example.npy', a)

In [50]:
a1 = np.load('example.npy')

In [51]:
a1

array([[1, 2, 3, 4]])

In [52]:
np.all(a1 == a)

True

### broadcasting

In [54]:
v = np.linspace(0,10,5)
v + 1

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

In [55]:
ones = np.ones((6, 5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
twos = np.ones((6,1)) * 2
ones + twos

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [62]:
twos = np.ones((6,2)) * 2
ones + twos

ValueError: operands could not be broadcast together with shapes (6,5) (6,2) 

### Check the speed of arrays

In [63]:
x = np.linspace(0,100,10000000)

In [64]:
x.size

10000000

In [65]:
import math
def get_lst(x):
    lst = []
    for i in x:
        lst.append(math.sin(i))
    return lst

In [66]:
%timeit get_lst(x)

4.65 s ± 30.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [67]:
%timeit np.sin(x)

56.6 ms ± 1.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [68]:
4.65 / 0.0566

82.15547703180214

*:)*