In [1]:
import numpy as np

In [2]:
v = np.linspace(0,10,5)
v

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [3]:
v[0]

0.0

In [4]:
v[1]

2.5

In [5]:
v[-1]

10.0

In [6]:
v[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [7]:
vv = np.random.random((5,4))

In [8]:
vv

array([[0.83604025, 0.92229374, 0.23910527, 0.93984345],
       [0.24120672, 0.79584668, 0.07449818, 0.65557434],
       [0.8594258 , 0.31326365, 0.54549279, 0.9918448 ],
       [0.01128156, 0.70380852, 0.33038012, 0.50382096],
       [0.4906658 , 0.89324981, 0.52681773, 0.16131931]])

In [10]:
vv[0,0]

0.8360402534900402

In [9]:
vv[4,3]

0.16131930972853925

In [11]:
ll = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
ll[1,2]

TypeError: list indices must be integers or slices, not tuple

In [13]:
ll[1][2]

6

In [14]:
v[2:4]

array([5. , 7.5])

In [15]:
vv[2:5,1]

array([0.31326365, 0.70380852, 0.89324981])

In [16]:
vv[2:5,1:2]

array([[0.31326365],
       [0.70380852],
       [0.89324981]])

In [17]:
vv[2:-1,:]

array([[0.8594258 , 0.31326365, 0.54549279, 0.9918448 ],
       [0.01128156, 0.70380852, 0.33038012, 0.50382096]])

In [19]:
vv

array([[0.83604025, 0.92229374, 0.23910527, 0.93984345],
       [0.24120672, 0.79584668, 0.07449818, 0.65557434],
       [0.8594258 , 0.31326365, 0.54549279, 0.9918448 ],
       [0.01128156, 0.70380852, 0.33038012, 0.50382096],
       [0.4906658 , 0.89324981, 0.52681773, 0.16131931]])

In [20]:
vv[:,::2]

array([[0.83604025, 0.23910527],
       [0.24120672, 0.07449818],
       [0.8594258 , 0.54549279],
       [0.01128156, 0.33038012],
       [0.4906658 , 0.52681773]])

In [23]:
v

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
v2 = v

In [25]:
v2

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [26]:
v2[2] = 0
v2

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

In [27]:
v

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

In [28]:
v3 = v[2:4].copy()

In [31]:
v3[0] = 1
v3

array([1. , 7.5])

In [32]:
v

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

### boolean mask

In [33]:
v

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

In [34]:
v[[0,2,4]]

array([ 0.,  0., 10.])

In [42]:
bool_index = v > 0
bool_index

array([False,  True, False,  True,  True])

In [43]:
v[bool_index]

array([ 2.5,  7.5, 10. ])

In [37]:
vv

array([[0.83604025, 0.92229374, 0.23910527, 0.93984345],
       [0.24120672, 0.79584668, 0.07449818, 0.65557434],
       [0.8594258 , 0.31326365, 0.54549279, 0.9918448 ],
       [0.01128156, 0.70380852, 0.33038012, 0.50382096],
       [0.4906658 , 0.89324981, 0.52681773, 0.16131931]])

In [44]:
vv[vv > 0.5] = 0.0
vv

array([[0.        , 0.        , 0.23910527, 0.        ],
       [0.24120672, 0.        , 0.07449818, 0.        ],
       [0.        , 0.31326365, 0.        , 0.        ],
       [0.01128156, 0.        , 0.33038012, 0.        ],
       [0.4906658 , 0.        , 0.        , 0.16131931]])

In [45]:
v

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

In [46]:
v[[0,3]] = [4,5]
v

array([ 4. ,  2.5,  0. ,  5. , 10. ])

*:)*