In [1]:
import numpy as np

In [2]:
array = np.random.standard_normal((4,5))
array

array([[-0.86642364,  0.08927528, -0.31172959, -1.08633193, -0.02183899],
       [-0.5527823 , -1.97904554,  0.36681884, -1.77124769,  1.24256504],
       [-0.88145363, -2.88652448, -0.71176248, -1.13080551, -0.92369397],
       [ 1.33957722,  0.26951458,  0.46724597, -0.21994167, -0.33211757]])

In [3]:
array.reshape((20,))

array([-0.86642364,  0.08927528, -0.31172959, -1.08633193, -0.02183899,
       -0.5527823 , -1.97904554,  0.36681884, -1.77124769,  1.24256504,
       -0.88145363, -2.88652448, -0.71176248, -1.13080551, -0.92369397,
        1.33957722,  0.26951458,  0.46724597, -0.21994167, -0.33211757])

In [6]:
array.reshape((2,10))

array([[-0.86642364,  0.08927528, -0.31172959, -1.08633193, -0.02183899,
        -0.5527823 , -1.97904554,  0.36681884, -1.77124769,  1.24256504],
       [-0.88145363, -2.88652448, -0.71176248, -1.13080551, -0.92369397,
         1.33957722,  0.26951458,  0.46724597, -0.21994167, -0.33211757]])

In [9]:
array.reshape((2, -1))

array([[-0.86642364,  0.08927528, -0.31172959, -1.08633193, -0.02183899,
        -0.5527823 , -1.97904554,  0.36681884, -1.77124769,  1.24256504],
       [-0.88145363, -2.88652448, -0.71176248, -1.13080551, -0.92369397,
         1.33957722,  0.26951458,  0.46724597, -0.21994167, -0.33211757]])

In [10]:
x = np.linspace(0,10,100)
sinx = np.sin(x)
cosx = np.cos(x)

In [12]:
np.dot(sinx, cosx)

1.6882473430775704

In [13]:
ones = np.ones((5,))
ones

array([1., 1., 1., 1., 1.])

In [14]:
line_space = np.linspace(-2, 2, 5)
line_space

array([-2., -1.,  0.,  1.,  2.])

In [15]:
rl = np.outer(ones, line_space)
rl

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

### np.dot

In [16]:
ones = np.ones((6,5)) * 3
ones

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [17]:
ones.shape

(6, 5)

In [18]:
ones_reshaped = ones.reshape(5,6)
ones_reshaped

array([[3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.]])

In [20]:
a = np.dot(ones_reshaped , ones)
a.shape

(5, 5)

### example:

In [21]:
A = np.array([[1,2],[3,5],[7,6]])
P = np.diag([5,5,5])
L = np.array([7,3, 2]).reshape((3,1))


# ((A'PA)^-1)(A'PL)

### check the shape and do A'PL

### numpy where

In [ ]:
array = np.array([1,2,3,4])
rows = np.where(array >= 2.5)
array[rows]

In [25]:
t = np.array([[1,2,3,'foo'],
 [2,3,4,'bar'],
 [5,6,7,'hello'],
 [8,9,1,'bar']])

In [26]:
rows , cols = np.where(t == 'bar')
t[rows]

array([['2', '3', '4', 'bar'],
       ['8', '9', '1', 'bar']], dtype='<U11')

In [27]:
rows, cols

(array([1, 3], dtype=int64), array([3, 3], dtype=int64))

In [28]:
array = np.random.standard_normal((5,5,3))
array

array([[[ 0.52244067, -0.25952951, -0.69496466],
        [ 1.30803882, -1.80737947,  1.95141509],
        [ 1.6370388 , -0.00702995,  1.2407647 ],
        [ 0.00927551, -0.38702801, -1.25331832],
        [ 1.42640831,  1.30628857,  0.66387472]],

       [[ 1.17219016,  0.05329882,  0.57942745],
        [ 1.25583739,  0.53266955,  0.74313159],
        [ 0.11287285,  1.52240463,  1.06094227],
        [-0.64866204, -0.0985188 , -0.89873218],
        [-0.0170527 ,  0.32089543,  0.46105796]],

       [[-0.85243741,  0.77528707, -1.88140457],
        [ 1.14351048, -2.42883188,  1.33719335],
        [-0.31717864,  0.4558675 , -0.25087043],
        [ 0.92297718,  1.76335905,  1.33434689],
        [-1.0926585 ,  1.45716157, -1.68074473]],

       [[ 0.64771609,  1.45130724,  2.01722474],
        [ 1.22926933, -0.35840774, -0.27353778],
        [-0.88801068,  0.93731239,  0.45141615],
        [-0.61349746, -0.71195081,  0.07462189],
        [-0.99674645,  0.01313449, -0.11643111]],

       [[ 1.

In [29]:
rows, cols, heights = np.where(array >= 1)
array[rows, cols, heights]

array([1.30803882, 1.95141509, 1.6370388 , 1.2407647 , 1.42640831,
       1.30628857, 1.17219016, 1.25583739, 1.52240463, 1.06094227,
       1.14351048, 1.33719335, 1.76335905, 1.33434689, 1.45716157,
       1.45130724, 2.01722474, 1.22926933, 1.51258274, 1.96110728,
       1.09464818, 1.80007221, 1.9147881 ])

*:)*